pinterest/doctorkafka

- kafkastats/src/main/java/com/pinterest/doctorkafka/util/KafkaUtils.java
- kafkastats/src/main/java/com/pinterest/doctorkafka/util/OperatorUtil.java
300ms timeout is very small for most environments. It's better to use the
zookeeper default timeout that is 30000ms.
As recommended in here:
https://github.com/sgroschupf/zkclient/blob/master/src/main/java/org/I0Itec/zkclient/ZkConnection.java#L44
> Increase session timeout to zookeeper default

- README.md
- drkafka/config/doctorkafka.properties
- drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
- drkafka/src/main/java/com/pinterest/doctorkafka/config/DoctorKafkaConfig.java
- kafkastats/src/main/java/com/pinterest/doctorkafka/stats/KafkaStatsMain.java
Makes the Ostrich service optional. Not all use cases have OpenTSDB and Ostrich. I also fixed a couple of typos along the way.
> Ostrich optional

- drkafka/src/main/java/com/pinterest/doctorkafka/servlet/DoctorKafkaBrokerStatsServlet.java
New stats return NaN sometimes.  Account for that.
Also fixes a trivial spelling error.
> NaN trouble

- drkafka/src/main/java/com/pinterest/doctorkafka/KafkaBroker.java
- drkafka/src/main/java/com/pinterest/doctorkafka/servlet/ClusterInfoServlet.java
- drkafka/src/main/java/com/pinterest/doctorkafka/servlet/DoctorKafkaBrokerStatsServlet.java
Switched out the set of data returned.
> Add max bytes in/out, remove complete stats set.

- drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
> Actually create a watcher to kill off DoctorKafka

- README.md
- kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsReporter.java
- kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsRetriever.java
- kafkastats/src/main/java/com/pinterest/doctorkafka/stats/KafkaStatsMain.java
> Disable collection of host data via ec2metadata command

- drkafka/src/main/java/com/pinterest/doctorkafka/servlet/ClusterInfoServlet.java
UI displaying wrong number of partitions due to miscalculation
> Fix Doctorkafka UI displaying wrong number of partitions

- drkafka/src/main/java/com/pinterest/doctorkafka/KafkaBroker.java
- drkafka/src/main/java/com/pinterest/doctorkafka/KafkaCluster.java
- drkafka/src/main/java/com/pinterest/doctorkafka/replicastats/ReplicaStatsManager.java
- drkafka/src/main/java/com/pinterest/doctorkafka/servlet/ClusterInfoServlet.java
- kafkastats/src/main/java/com/pinterest/doctorkafka/util/OperatorUtil.java
1. Remove large chunks of blocking single-thread code
2. Reuse avro deserializer
> Optimize launch time

- pom.xml
This will help releasing to maven
> Sign root level pom.xml with gpg plugin

- README.md
- drkafka/pom.xml
- drkafka/src/main/java/com/pinterest/doctorkafka/servlet/ClusterInfoServlet.java
- kafkastats/pom.xml
- pom.xml
update contributor list, and had some format change.
> update contributors list, and format change in ClusterInfoServlet.java

- kafkastats/src/main/java/com/pinterest/doctorkafka/tools/BrokerStatsReader.java
Removed faulty security protocol option from brokerstats reader tool
> Remove unused security protocol option in brokerstats reader tool

- drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafka.java
- drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
- drkafka/src/main/java/com/pinterest/doctorkafka/KafkaBroker.java
- drkafka/src/main/java/com/pinterest/doctorkafka/KafkaCluster.java
- drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java
- drkafka/src/main/java/com/pinterest/doctorkafka/replicastats/BrokerStatsProcessor.java
- drkafka/src/main/java/com/pinterest/doctorkafka/replicastats/PastReplicaStatsProcessor.java
- drkafka/src/main/java/com/pinterest/doctorkafka/replicastats/ReplicaStatsManager.java
- drkafka/src/main/java/com/pinterest/doctorkafka/servlet/KafkaTopicStatsServlet.java
- drkafka/src/main/java/com/pinterest/doctorkafka/tools/BrokerStatsFilter.java
- drkafka/src/main/java/com/pinterest/doctorkafka/tools/ClusterLoadBalancer.java
- drkafka/src/main/java/com/pinterest/doctorkafka/tools/ReplicaStatsRetriever.java
- drkafka/src/main/java/com/pinterest/doctorkafka/util/ReplicaStatsUtil.java
- drkafka/src/test/java/com/pinterest/doctorkafka/ClusterInfoServletTest.java
- drkafka/src/test/java/com/pinterest/doctorkafka/KafkaBrokerTest.java
- drkafka/src/test/java/com/pinterest/doctorkafka/KafkaClusterManagerTest.java
- drkafka/src/test/java/com/pinterest/doctorkafka/KafkaClusterTest.java
- drkafka/src/test/java/com/pinterest/doctorkafka/ReplicaStatsManagerTest.java
Refactored ReplicaStatsManager static usage
This will make testing simpler by allowing mocking
cc: @ambud
> refactor ReplicaStatsManager static methods

- drkafka/src/main/java/com/pinterest/doctorkafka/servlet/DoctorKafkaActionsServlet.java
Changed hour format to reduce confusion
> Fix action reporter hour format and add timezone

- drkafka/src/main/java/com/pinterest/doctorkafka/config/DoctorKafkaConfig.java
> Remove hard-coded config path

- kafkastats/src/main/java/com/pinterest/doctorkafka/stats/ReplicaStatsTask.java
Patching 0.3.x branch with #184
> Patch kafkastats from 0.2.4.8

- drkafka/pom.xml
- pom.xml
bump dropwizard version to 1.3.15 and remove patch dependencies of jetty and jackson
> bump dropwizard version to 1.3.15 

- drkafka/pom.xml
- kafkastats/pom.xml
Patching release profile configs from 0.3.0-rc.1
> Fix release profile

- drkafka/scripts/configuration_validator.sh
- drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java
- drkafka/src/main/java/com/pinterest/doctorkafka/tools/ConfigurationValidator.java
Add a simple validation tool for verifying that the plugin configs work
> Add configuration validator tool

- drkafka/pom.xml
- drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
- drkafka/src/main/java/com/pinterest/doctorkafka/plugins/operator/cluster/kafka/URPReassignmentOperator.java
- drkafka/src/main/java/com/pinterest/doctorkafka/plugins/task/cluster/kafka/KafkaReportOperationTaskHandler.java
- drkafka/src/main/java/com/pinterest/doctorkafka/tools/BrokerStatsFilter.java
- kafkastats/src/main/java/com/pinterest/doctorkafka/util/KafkaUtils.java
- kafkastats/src/main/java/com/pinterest/doctorkafka/util/OperatorUtil.java
- pom.xml
Also, simplified the broker availability check by calling a metadata fetch API instead of fetching messages.
> Upgrade Kafka client library version in use to 2.0

- drkafka/pom.xml
> Fix guava version

- README.md
Update readme to add Orion info.
> Update readme to add Orion info
