pinterest/doctorkafka

drkafka/doctorkafka.iml
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java
drkafka/src/main/java/com/pinterest/doctorkafka/notification/Email.java
kafkastats/kafkastats.iml
kafkastats/src/main/java/com/pinterest/doctorkafka/util/OperatorUtil.java
pom.xml

This PR removes the javafx dependency, enabling OpenJDK builds without Openjfx.
Fixing: https://github.com/pinterest/doctorkafka/issues/3

Replacing javafx.util.Pair with org.apache.commons.lang3.tuple.MutablePair

---

drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java

It looks like that,
the runner is using a properties file instead of cli options,
but the cli options are still there, so I imagine that they're not required.

Fixing drkafka runner

---

pom.xml

Kafkastats was complaining about:
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonMerge
so add jackson-core 2.8.9 as dependecy.
Also update jackson-module-scala_2.12 to 2.9.0 because of:
Exception in thread "main" com.fasterxml.jackson.databind.JsonMappingException: Scala module 2.8.4 requires Jackson Databind version >= 2.8.0 and < 2.9.0
The software does compile and start even though the dependncies are off,
but it doesn't really work (it cannot parse ZK responses etc. so it
keeps running and logging errors).

Add missing dependencies to pom.xml

---

kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsRetriever.java

Kafka supports specifying multiple log dirs separated with commas. This
commit fixes that issue where user might have specified multiple log
dirs.
Kafka writes the meta.properties to all log dirs, so it's safe to assume
that if we take the first one it'll be good enough.

Fix parsing issues if logdirs contain commas

---

drkafka/src/main/java/com/pinterest/doctorkafka/replicastats/ReplicaStatsManager.java
drkafka/src/main/java/com/pinterest/doctorkafka/tools/BrokerStatsFilter.java
kafkastats/src/main/java/com/pinterest/doctorkafka/util/KafkaUtils.java

Because of the way kafkaconsumer objects are stored and accessed through
KafkaUtils we need to delete those objects upon connection close,
otherwise if we get the object using zkconnectionurl -string we get an
consumer object that has already been closed.
Using an object that is already closed will cause
java.lang.IllegalStateException and that's of course not a perfect
situation. This change also allows using the same zk connectstring for
managed cluster and kafkastats, which especially makes development
easier because you don't have to setup two clusters.
A better fix would probably be to inherit KafkaConsumer and make the
close to make sure that the object gets alos deleted from everywhere
else, but this is sufficient enough at this point.

When closing consumer also delete from hashmap

---

kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsRetriever.java

The original implementation assumed that there's always just one log
dir. In larger kafka brokers there's usually multiple kafka log dirs, so
we need to take that into account when running the
setBrokerConfiguration -function.

Detection for diskfailure with multiple log dirs

---

drkafka/src/main/java/com/pinterest/doctorkafka/KafkaBroker.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java
drkafka/src/main/java/com/pinterest/doctorkafka/notification/Email.java
drkafka/src/main/java/com/pinterest/doctorkafka/util/UnderReplicatedReason.java
kafkastats/src/main/java/com/pinterest/doctorkafka/util/OperatorUtil.java

Currently Dr. Kafka only checks port 9092 to verify whether a broker is live or dead.  But in opeartion, we saw quite a few times that a broker is hanging but can still show port 9092 as active.
Added more checks (fetch an offset and then fetch data from the offset for that offset) to verfy whether the broker is really dead or alive.
On the next checkin, I will add some automatic active code for dead broker

Doctor Kafka enhancement: adding the capabilty to fetch offset/data

---

drkafka/src/main/java/com/pinterest/doctorkafka/servlet/KafkaTopicStatsServlet.java
drkafka/src/main/java/com/pinterest/doctorkafka/tools/ClusterLoadBalancer.java

Also pulls in a trivial guard for the balancer to not throw an exception when there are no busy nodes, because that's kind of/sort of like UI.

Ui disambiguation

---

drkafka/Dockerfile
drkafka/pom.xml
drkafka/scripts/action_retriever.sh
drkafka/scripts/run.sh
drkafka/scripts/run_dev.sh
drkafka/src/main/resources/versioning.properties
kafkastats/pom.xml
kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsReporter.java
kafkastats/src/main/java/com/pinterest/doctorkafka/stats/KafkaAvroPublisher.java
kafkastats/src/main/java/com/pinterest/doctorkafka/stats/KafkaStatsMain.java
pom.xml

make avroProducer shared across threads to reduce connection counts to brokers
make kafkastats shutdown more graceful
make avroPublisher available to shutdown thread and expose underlying producer.close()
bumped version also

reduce connection counts from KafkaStats via sharing producer

---

kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsReporter.java
kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsRetriever.java
kafkastats/src/main/java/com/pinterest/doctorkafka/stats/KafkaAvroPublisher.java
kafkastats/src/main/java/com/pinterest/doctorkafka/stats/KafkaMetricRetrievingTask.java
kafkastats/src/main/java/com/pinterest/doctorkafka/stats/KafkaStatsMain.java

Add system network stats (interface stats) to Dr.Kafka:
- can be used for more accurate load calculation during rebalancing
- apply network load limits to Kafka brokers for partition assignment
Cleaning up unused imports / code
Fixing generics

Add system network stats (interface stats) to Dr.Kafka

---

README.md
docs/APIs.md
drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafka.java
drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/BrokerApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/ClusterApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/MaintenanceApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/notification/Email.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/DoctorKafkaInfoServlet.java

**Purpose:**
Support for cluster maintenance mode to temporarily pause Doctor Kafka operations on a cluster.
**Description:**
Maintenance mode will disable Doctor Kafka for a cluster so manual operations like broker replacement, restarts etc. can be performed without triggering automated rebalances or broker replacements.
**APIs:**
```
curl -XGET http://localhost:8080/api/cluster/<clustername>/admin/maintenance
curl -XPUT http://localhost:8080/api/cluster/<clustername>/admin/maintenance
curl -XDELETE http://localhost:8080/api/cluster/<clustername>/admin/maintenance
```
```
curl -XGET http://localhost:8080/api/cluster
```

Support for cluster maintenance mode

---

kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsRetriever.java

From the Kafka documentation, security.inter.broker.protocol has a default value of PLAINTEXT, so let's assume that's what it is for people who do not keep default values in their configuration files.

PLAINTEXT is the default

---

drkafka/src/main/java/com/pinterest/doctorkafka/KafkaBroker.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaCluster.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java
drkafka/src/main/java/com/pinterest/doctorkafka/errors/ClusterInfoError.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/ClusterInfoServlet.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/DoctorKafkaActionsServlet.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/DoctorKafkaBrokerStatsServlet.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/DoctorKafkaInfoServlet.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/DoctorKafkaServletUtil.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/KafkaTopicStatsServlet.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/UnderReplicatedPartitionsServlet.java
drkafka/src/test/java/com/pinterest/doctorkafka/ClusterInfoServletTest.java
pom.xml

This replaces #28 .  I messed up a rebase there and the PR is all wonky now.  This is much cleaner.
WIth this patch, the standard servlets respond to a Content-Header of "application/json" by returning JSON content instead of the usual HTML, which is a fairly standard convention for web applications.

New PR for adding JSON output to the standard servlets

---

kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsRetriever.java

Disable network stats related computation that was introduced in  https://github.com/pinterest/doctorkafka/commit/2d6a8971b1babd82ff42d49421322dcbf7825bdf

disable network stats computation in kafkastats

---

README.md

This PR does a couple of things to the README
1. Updates jar version numbers and usage information for `kafkastats`, `drkafka`, and the `ClusterLoadBalancer`
2. Clarifies the role of the `dropwizard_yaml_file`
3. Removes trailing whitespace
I found the original README to be a little misleading where the usage information was incomplete. I hope this helps others get up and running a little more quickly.

Update README to latest jar version and include new kafkastats args

---

drkafka/pom.xml
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaCluster.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java
drkafka/src/test/java/com/pinterest/doctorkafka/KafkaClusterTest.java

Addressing #18
Duplicate reassignment will happen when multiple outOfSyncReplicas exist and target broker is still least used broker.
Creating the broker queue each time so we don't need to deal with recovering the brokerQueue for next outOfSyncReplica

Fix #18 duplicate reassignment

---

drkafka/config/doctorkafka.properties
drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
drkafka/src/main/java/com/pinterest/doctorkafka/config/DoctorKafkaConfig.java

Adding a configuration to disable the restarting doctorkafka, this option defaults to false, i.e. restart is on by default.

Add option to disable restart

---

drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafka.java
drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaHeartbeat.java
drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMetrics.java
drkafka/src/main/java/com/pinterest/doctorkafka/replicastats/BrokerStatsProcessor.java
drkafka/src/main/java/com/pinterest/doctorkafka/replicastats/PastReplicaStatsProcessor.java
kafkastats/src/main/java/com/pinterest/doctorkafka/stats/KafkaStatsMain.java
kafkastats/src/main/java/com/pinterest/doctorkafka/util/OperatorUtil.java

1. Create a heartbeat thread that publishes heartbeat metrics once the backfilling is finished
2. Modifications of the signature of ostrich initializer to distinguish kafkastats agent and doctorkafka service metrics.

Added heartbeat metric and a few other metric-related fixes

---

drkafka/pom.xml

https://github.com/pinterest/doctorkafka/network/alert/drkafka/pom.xml/org.eclipse.jetty:jetty-server/open
CVE-2019-10247 More information
moderate severity
Vulnerable versions: >= 9.4.0, < 9.4.17.v20190418
Patched version: 9.4.17.v20190418
In Eclipse Jetty version 7.x, 8.x, 9.2.27 and older, 9.3.26 and older, and 9.4.16 and older, the server running on any OS and Jetty version combination will reveal the configured fully qualified directory base resource location on the output of the 404 error for not finding a Context that matches the requested path. The default server behavior on jetty-distribution and jetty-home will include at the end of the Handler tree a DefaultHandler, which is responsible for reporting this 404 error, it presents the various configured contexts as HTML for users …

bump up jetty-server version to 9.4.17.v20190418

---

drkafka/src/main/java/com/pinterest/doctorkafka/KafkaBroker.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaCluster.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java
drkafka/src/main/java/com/pinterest/doctorkafka/config/DoctorKafkaClusterConfig.java
drkafka/src/test/java/com/pinterest/doctorkafka/KafkaClusterTest.java

This is the first part for locality-aware reassignments using rackId/availability zone info. Currently it will not failover to other localities nor will it balance replicas throughout the localities. These issues will be issued afterwards.

Add simple logic locality-awareness reassignments

---

drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
drkafka/src/main/java/com/pinterest/doctorkafka/config/DoctorKafkaConfig.java

Bind host configuration will allow dr. kafka to be run in localhost mode only so it can be run behind auth proxies.

Add bindhost configuration

---

drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java

Previously dry runs would not prevent broker replacement.

Add safeguard so that dry-runs won't perform replacement actions

---

drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaBroker.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaCluster.java
drkafka/src/main/java/com/pinterest/doctorkafka/KafkaClusterManager.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/BrokersApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/BrokersDecommissionApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/ClustersApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/ClustersMaintenanceApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/DoctorKafkaApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/notification/Email.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/ClusterInfoServlet.java
drkafka/src/main/java/com/pinterest/doctorkafka/servlet/DoctorKafkaBrokerStatsServlet.java
drkafka/src/main/java/com/pinterest/doctorkafka/util/ApiUtils.java
drkafka/src/main/java/com/pinterest/doctorkafka/util/ReassignmentInfo.java
drkafka/src/test/java/com/pinterest/doctorkafka/KafkaClusterTest.java

1. Added Broker decommissioning API endpoint
2. Expose decommission status in UI
3. Small refactor of API code for reusability
Notes: 
Currently, a decommissioned broker
* WILL:
1. Be ignored when checking for dead brokers (and thus no replacement will happen)
2. Be ignored during URP reassignments
3. Still update stats so it can catch up if decommission is cancelled
* WILL NOT:
1. Reassign the partitions to other brokers, you have to do it manually
Decommissioning is ephemeral for now, state is not preserved in ZK, so if a restart happens, we will have to do it again

Add broker decommission api

---

drkafka/pom.xml

We are hitting this issue https://github.com/eclipse/jetty.project/pull/3550 after patching jetty to 9.4.17.v20190418. Upgrading jetty to 9.4.18 to fix issue.
Also upgrading dropwizard from 1.3.8 to 1.3.10.

Upgrade jetty to 9.4.18.v20190429 and dropwizard to 1.3.10

---

docs/APIs.md
drkafka/src/main/java/com/pinterest/doctorkafka/DoctorKafkaMain.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/BrokersApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/BrokersDecommissionApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/ClustersMaintenanceApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/api/DoctorKafkaApi.java
drkafka/src/main/java/com/pinterest/doctorkafka/config/DoctorKafkaConfig.java
drkafka/src/main/java/com/pinterest/doctorkafka/security/DrKafkaAuthorizationFilter.java
drkafka/src/main/java/com/pinterest/doctorkafka/security/DrKafkaSecurityContext.java
drkafka/src/main/java/com/pinterest/doctorkafka/security/SampleAuthorizationFilter.java
drkafka/src/main/java/com/pinterest/doctorkafka/security/UserPrincipal.java

**Summary**
Dr. Kafka now has some privileged operations exposed via API like broker decomissioning and maintenance mode. These operations should be restricted to admin users only. This PR allows a configurable authorization provider to be added to Dr. Kafka to limit this access.
**Description**
- Access is restricted to dr_kafka_admin role
- Restrictions can be applied using standard JAX-RS annotations
- Authorization Filter is responsible to map group to role
- Pluggable authorization filters can be implemented by implementing com.pinterest.doctorkafka.security.DrKafkaAuthorizationFilter
- Sample implementation is provided via com.pinterest.doctorkafka.security.ExampleAuthorizationFilter

Adding authorization capabilities to Dr. Kafka to restrict privileged operations

---

kafkastats/pom.xml

1.9.0 breaks the build, pinning avro-maven-plugin to previous released version.

pin avro plugin version to 1.8.2

---

drkafka/pom.xml

This is to address the security alert on jackson-databind. See the following link for details. 
https://github.com/pinterest/doctorkafka/network/alert/drkafka/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

bump jackson-databind version from 2.9.8 to 2.9.9

---

drkafka/pom.xml

Update  jackson-databind to 2.9.9.1 for the security alert. 
https://github.com/pinterest/doctorkafka/network/alert/drkafka/pom.xml/com.fasterxml.jackson.core:jackson-databind/open
CVE-2019-12814 More information
moderate severity
Vulnerable versions: >= 2.0.0, < 2.9.9.1
Patched version: 2.9.9.1
A Polymorphic Typing issue was discovered in FasterXML jackson-databind 2.x through 2.9.9. When 
Default Typing is enabled (either globally or for a specific property) for an externally exposed JSON 
endpoint and the service has JDOM 1.x or 2.x jar in the classpath, an attacker can send a specifically 
crafted JSON message that allows them to read arbitrary local files on the server.

update jackson-databind to 2.9.9.1

---

drkafka/pom.xml

version bump 2.9.9.1 is only available for `jackson-databind`

Fix jackson-databind 2.9.9.1 version issue

---

drkafka/src/main/java/com/pinterest/doctorkafka/KafkaCluster.java
drkafka/src/main/java/com/pinterest/doctorkafka/modules/monitor/cluster/kafka/BrokerStatsMonitor.java
drkafka/src/test/java/com/pinterest/doctorkafka/ClusterInfoServletTest.java
drkafka/src/test/java/com/pinterest/doctorkafka/KafkaBrokerTest.java
drkafka/src/test/java/com/pinterest/doctorkafka/KafkaClusterTest.java
kafkastats/src/main/java/com/pinterest/doctorkafka/util/OperatorUtil.java

Consolidation of BrokerStatsMonitor 
1. Make KafkaCluster sliding window configurable
2. Removing auto-commit completely from BrokerStatsMonitor Kafka consumers.
BrokerStatsMonitor long-running processor will now assign to TopicPartitions manually and seek to offsets left over from the back-fill processors.
Previously the behaviour was to commit and use high level kafka subscriptions, which is inefficient since the restart might be a while later and unnecessary messages would be read.

Fix BrokerStatsMonitor issues

---

drkafka/pom.xml

Remediation
Upgrade com.fasterxml.jackson.core:jackson-databind to version 2.9.9.2 or later. For example:
<dependency>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-databind</artifactId>
<version>[2.9.9.2,)</version>
</dependency>
https://github.com/pinterest/doctorkafka/network/alert/drkafka/pom.xml/com.fasterxml.jackson.core:jackson-databind/open

fix com.fasterxml.jackson.core:jackson-databind security alert

---

drkafka/config/doctorkafka.config.yaml

Fix a few typos in event name in `doctorkafka.config.yaml`

Fix typos in config

---

drkafka/src/main/java/com/pinterest/doctorkafka/plugins/operator/cluster/kafka/URPReassignmentOperator.java

Previously the operator config for max bandwidth was in bytes, fixed it to MBs

Fix wrong URPReassignmentOperator config calculation

---

kafkastats/src/main/java/com/pinterest/doctorkafka/stats/BrokerStatsRetriever.java

If we are to use `ec2metadata`, and ec2 instances do not have hostname set explicitly, then the name field will not be populated, causing drkafka ignoring the record: https://github.com/pinterest/doctorkafka/blob/ee5c005328047407782832f432911fa08f2199b3/drkafka/src/main/java/com/pinterest/doctorkafka/replicastats/BrokerStatsProcessor.java#L76
This change sets the name field to hostname by default.

let kafkastats set broker's name to hostname by default

---

kafkastats/src/main/java/com/pinterest/doctorkafka/stats/ReplicaStatsTask.java

Kafka sometimes have stale metadata for leader partitions which will block the stats publishing. Catch this exception like other JMX metrics below.

Catch exception when populating ReplicaStats in KafkaStats
